eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka, http://localhost:8888/eureka
feign:
  okhttp:
    enabled: true