server:
  port: 8081
spring:
  application:
    name: pharmacy-service  
  profiles:
    active: test
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
