---
spring:
  application:
    name: athenaeurekamaster
  config:
    activate:
      on-profile: master
server:
  port: 8889      
eureka:      
  client:
    register-with-eureka: false
    fetch-registry: false
...
---    
server:
  port: 8888
spring:
  application:
    name: athenaeurekaslave
  config:
    activate:
      on-profile: slave
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8889/eureka      
...          